const texts = {
  home: "home",
  login: "Login",
  email: "Email",
  loginError: "This field is required",
  password: "Password",
  submit: "Submit",
  loginRedirect: "Not registered yet?",
  loginRedirectLink: "Click here to sign up!",
  fullName: "Full Name",
  signUpFullNameError: "Full Name is required",
  signUpEmailError: "Email is required",
  signUpPassError: "Password is Required",
  signUpErrorRegEx:
    "Password must be at least 8 characters long and contain at least one letter and one number",
  description: "Description",
  signUpDescriptionPlaceholder:
    "Write a brief description about yourself, who you are and what you do, it must be at at least 20 characters long and max. 500 characters long",
  signUpDesriptionErrorOne: "Description is required",
  signUpDescriptionTwo: "Description must be at least 20 characters long",
  signUpDescriptionThree: "Description cannot exceed 500 characters",
  contactInfo: "Contact Information",
  signUpContactInfoPlaceHolder:
    "Phone Number, LinkedIn, alternate email, etc...",
  signUpContactInfoError: "Contact Info is required",
  signUpAddButton: "Add Contact Information",
  remove: "Remove",
  signUpPFP: "Upload a Profile Picture (optional)",
  signUpPFPPlaceHolder: "Click here to add you profile picture!",
  signUpSuccess: "Account created successfully",
  signUpError: "There was an error creating your account",
  signUpRedirect: "Already have an account?",
  signUpRedirectLink: "Click here to log in!",
  menuAllUsers: "Look for a user",
  profile: "Profile",
  portfolio: "Portfolio",
  logout: "Logout",
  signup: "Signup",
  portoflioFirstTitle: "Your projects",
  portoflioSecondTitle: "Add a project",
  delete: "Delete",
  edit: "Edit",
};

export default texts;
