const texts = {
  home: 'home',
  login: 'Login',
  email: 'Email',
  loginError: 'This field is required',
  password: 'Password',
  submit: 'Submit',
  loginRedirect: 'Not registered yet?',
  loginRedirectLink: 'Click here to sign up!',
  fullName: 'Full Name',
  signUpFullNameError: 'Full Name is required',
  signUpEmailError: 'Email is required',
  signUpPassError: 'Password is Required',
  signUpErrorRegEx:
    'Password must be at least 8 characters long and contain at least one letter and one number',
  description: 'Description',
  signUpDescriptionPlaceholder:
    'Write a brief description about yourself, who you are and what you do, it must be at at least 20 characters long and max. 500 characters long',
  signUpDesriptionErrorOne: 'Description is required',
  signUpDescriptionTwo: 'Description must be at least 20 characters long',
  signUpDescriptionThree: 'Description cannot exceed 500 characters',
  contactInfo: 'Contact Information',
  signUpContactInfoPlaceHolder:
    'Phone Number, LinkedIn, alternate email, etc...',
  signUpContactInfoError: 'Contact Info is required',
  signUpAddButton: 'Add Contact Information',
  remove: 'Remove',
  signUpPFP: 'Upload a Profile Picture (optional)',
  signUpPFPPlaceHolder: 'Click here to add you profile picture!',
  signUpSuccess: 'Account created successfully, now please log in',
  signUpError: 'There was an error creating your account',
  signUpRedirect: 'Already have an account?',
  signUpRedirectLink: 'Click here to log in!',
  menuAllUsers: 'Look for a user',
  profile: 'Profile',
  portfolio: 'Portfolio',
  logout: 'Logout',
  signup: 'Signup',
  portoflioFirstTitle: 'Your projects',
  portoflioSecondTitle: 'Add a project',
  delete: 'Delete',
  edit: 'Edit',
  portfolioText:
    'Here you can see your projects, delete or edit them or create a new project.',
  deleteProjectWarning:
    'Are you sure you want to delete this project? This action cannot be undone.',
  deleteProjectSuccess: 'Project deleted Successfully',
  deleteProjectError: 'Failed to delete the project',
  projectsMissing: 'No projects to show at them moment.',
  newProjectFormTitle: 'Create a new project for your portfolio',
  newProjectSuccess: 'Project created succesfully!',
  newProjectError: 'Error creating the project, please try again later.',
  newProjectTitle: 'New Project Title',
  newProjectTitleError: 'You must provide a title for this project',
  newProjectDescription: 'New project description',
  newProjectDescriptionPlaceHolder: 'Write a description about this project.',
  newProjectDescriptionError: 'Project must have a description',
  newProjedctDescriptionErrorTwo:
    'The project description must be at least 20 characters long.',
  newProjedctDescriptionErrorThree:
    'The description for this poject can\'t be longer than 500 characters long.',
  newProjectLink: 'Project Link',
  newProjectLinkPlaceHolder:
    'Links associated with the project, can be repository, deploy link, etc.',
  newProjectLinkError: 'You must provide a link',
  newProjectAddLink: 'Add another link',
  newProjectImage: 'Project Image',
  newProjectImagePlaceHolder: 'Upload an image associated with the  project.',
  newProjectImageError: 'You must provide an image.',
  newProjectImageAdd: 'Add another image',
};

export default texts;
